const data = {
    productos: [
      {
        _id: '1',
        nombre: 'Lentejas con verduras',
        category: 'Shirts',
        image: '/images/lentejas1.jpg',
        precio: 5,
        stock: 6,
        brand: 'Nike',
        rating: 4.5,
        numeroreseñas: 10,
        descripcion: 'high quality product',
      },
      {
        _id: '2',
        nombre: 'Lentejas con verduras',
        category: 'Shirts',
        image: '/images/lentejas1.jpg',
        precio: 5,
        stock: 6,
        brand: 'Adidas',
        rating: 4.0,
        numeroreseñas: 10,
        descripcion: 'high quality product',
      },
      {
        _id: '3',
        nombre: 'Lentejas con verduras',
        category: 'Shirts',
        image: '/images/lentejas1.jpg',
        precio: 5,
        stock: 1,
        brand: 'Lacoste',
        rating: 4.8,
        numeroreseñas: 17,
        descripcion: 'high quality product',
      },
      {
        _id: '4',
        nombre: 'Lentejas con verduras',
        category: 'Pants',
        image: '/images/lentejas1.jpg',
        precio: 5,
        stock: 3,
        brand: 'Nike',
        rating: 4.5,
        numeroreseñas: 14,
        descripcion: 'high quality product',
      },
      {
        _id: '5',
        nombre: 'Lentejas con verduras',
        category: 'Pants',
        image: '/images/lentejas1.jpg',
        precio: 5,
        stock: 4,
        brand: 'Puma',
        rating: 4.5,
        numeroreseñas: 10,
        descripcion: 'high quality product',
      },
      {
        _id: '6',
        nombre: 'Lentejas con verduras',
        category: 'Pants',
        image: '/images/lentejas1.jpg',
        precio: 5,
        stock: 7,
        brand: 'Adidas',
        rating: 4.5,
        numeroreseñas: 15,
        descripcion: 'high quality product',
      },
    ],
  };
  export default data;